### ISSUE TITLE
 Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=5.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

### ISSUE THREAD

**Issue by xyfy** [abpframework/eShopOnAbp#2]
when clone the source ,and `dotnet run` in **auth-server** folder

got an err

``` text
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=5.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. 系统找不到指定的文件。
File name: 'Microsoft.EntityFrameworkCore, Version=5.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

I found the **5.0.7** version in bin ,but not **5.0.8**

**Comment by xyfy** [comment]
I see the `Volo.Abp.EntityFrameworkCore.SqlServer` 4.4.0-rc1  depend on **Microsoft.EntityFrameworkCore.SqlServer** 5.0.7

**Comment by gterdem** [comment]
It is local nuget reference version mismatch error. We don't specify version but we are thinking about that since this became a common problem.
https://github.com/abpframework/abp/blob/2fbd07e147418e0e080a8904d0509337fc8f3173/framework/src/Volo.Abp.EntityFrameworkCore.SqlServer/Volo.Abp.EntityFrameworkCore.SqlServer.csproj#L22

Try **removing** lines shown below from all microservice efcore layers:
https://github.com/abpframework/eShopOnAbp/blob/f2387835d6ca526725ddd31a0a65192f1eb445eb/services/administration/src/EShopOnAbp.AdministrationService.EntityFrameworkCore/EShopOnAbp.AdministrationService.EntityFrameworkCore.csproj#L10-L11

**Comment by hitaspdotnet** [comment]
replace 
```csharp
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.*">
```
with
```csharp
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.7">
```
